name: "✨ Feature request"
description: "Suggest an idea for this project"
labels: [ "✨ enhancement", "👀 evaluation" ]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure that our feature request form is appropriate for you.
      options:
        - label: I read and understood the **[Contributing Guidelines](https://github.com/Abrynos/ShoppingList/blob/main/.github/CONTRIBUTING.md)**.
          required: true
        - label: This is not a **[question](https://github.com/Abrynos/ShoppingList/discussions)**.
          required: true
        - label: This is not a **[technical issue](https://github.com/Abrynos/ShoppingList/discussions)**.
          required: true
        - label: This is not a **[duplicate](https://github.com/Abrynos/ShoppingList/issues)** of an existing issue.
          required: true
        - label: This idea is not already possible.
          required: true
        - label: I believe my idea falls into the projects scope and should be offered as part of the built-in functionality.
          required: true

  - type: textarea
    id: feature-purpose
    attributes:
      label: Purpose
      description: Purpose of the new feature - if it solves some problem, precise which in particular. If it benefits the application in some other way, precise why in particular.
      placeholder: |
        Present the underlying reason why this enhancement makes sense and what the context of it is.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What would you like to see as a solution to the purpose specified above?
      placeholder: |
        What would work for you?
    validations:
      required: true

  - type: textarea
    id: sufficiency
    attributes:
      label: Why are the currently available solutions not sufficient?
      description: Evaluate the existing solutions in regards to your requirements.
      placeholder: |
        If something you are suggesting is already possible, then explain to us why the currently available solutions are not sufficient.

        If it's not possible yet, then explain to us why it should be.
    validations:
      required: true

  - type: dropdown
    id: help
    attributes:
      label: Can you help us with this feature request?
      description: This application is offered for free and our resources are limited. Helping us increases the chance of making it happen.
      options:
        - Yes, I can code the solution myself and send a merge request.
        - Somehow, I can test and offer feedback, but I can't code the solution.
        - No, I don't have time, skills or willings for any of that.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Everything else you consider note-worthy that we didn't ask for.

  - type: markdown
    attributes:
      value: |
        ---
        #### Thank you for taking the time to fill out this bug report.
