name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CHANGELOG_FILE: CHANGELOG.txt

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: set-env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - id: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_VERSION }}
      - id: setup-jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 13
      - id: prepare-secrets
        run: |
          echo "${{ secrets.KEYSTORE }}" > keystore.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch keystore.jks.asc > app/keystore.jks
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" > keystore.properties.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}" --batch keystore.properties.asc > keystore.properties
          rm keystore.jks.asc
          rm keystore.properties.asc
      - id: prepare-build
        run: chmod +x ./gradlew
      - id: build
        run: ./gradlew build
      - id: prepare-changelog
        run: |
          echo "# Changes" > "${{ env.CHANGELOG_FILE }}"
          sed "s/^* /- /g" "fastlane/metadata/android/en-US/changelogs/$(grep versionCode app/build.gradle | grep -E '[0-9]+' --only-matching).txt" >> "${{ env.CHANGELOG_FILE }}"
      - id: create-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: app/build/outputs/apk/release/app-release.apk
          body_path: "${{ env.CHANGELOG_FILE }}"
          tag_name: ${{ env.RELEASE_VERSION }}

