name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CHANGELOG_FILE: CHANGELOG.txt

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: set-env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_VERSION }}
      - id: setup-jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 13
      - id: prepare-build
        run: chmod +x ./gradlew
      - id: decode-keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "keystore.jks"
          encodedString: ${{ secrets.KEYSTORE }}
      - id: build
        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=${{ steps.decode-keystore.outputs.filePath }} -Pandroid.injected.signing.store.password=${{ secrets.PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.PASSWORD }}
      - id: prepare-changelog
        run: |
          echo "# Changes" > "${{ env.CHANGELOG_FILE }}"
          sed "s/^* /- /g" "fastlane/metadata/android/en-US/changelogs/$(grep versionCode app/build.gradle | grep -E '[0-9]+' --only-matching).txt" >> "${{ env.CHANGELOG_FILE }}"
      - id: create-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: app/build/outputs/apk/release/*.apk
          body_path: "${{ env.CHANGELOG_FILE }}"
          tag_name: ${{ env.RELEASE_VERSION }}

