name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CHANGELOG_FILE: CHANGELOG.txt

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: set-env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_VERSION }}
      - id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - id: setup-gradle
        uses: gradle/actions/setup-gradle@v4
      - id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: keystore.jks
          encodedString: ${{ secrets.KEYSTORE }}
      - id: build
        run: ./gradlew build -Pandroid.injected.signing.store.file=${{ steps.decode_keystore.outputs.filePath }} -Pandroid.injected.signing.store.password=${{ secrets.PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.PASSWORD }} -Pandroid.injected.signing.v1-enabled=true -Pandroid.injected.signing.v2-enabled=true
      - id: prepare-changelog
        run: |
          echo "# Changes" > "${{ env.CHANGELOG_FILE }}"
          sed "s/^* /- /g" "fastlane/metadata/android/en-US/changelogs/$(grep versionCode app/build.gradle.kts | grep -E '[0-9]+' --only-matching).txt" >> "${{ env.CHANGELOG_FILE }}"
      - id: create-release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: app/build/outputs/apk/release/*.apk
          body_path: "${{ env.CHANGELOG_FILE }}"
          tag_name: ${{ env.RELEASE_VERSION }}

